# Use the PHP with Apache image
FROM php:8.2.12-apache

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y \
    libzip-dev \
    zip \
    git \
    unzip

# Enable mod_rewrite
RUN a2enmod rewrite

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql zip

# Set the document root to the public directory
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Set the working directory to where the application will be located
WORKDIR /var/www/html

# Copy composer.json and composer.lock if it exists from LaravelMavericksFront to the working directory
COPY LaravelMavericksFront/composer.json ./
COPY LaravelMavericksFront/composer.lock ./  # Optional, only if you have this file

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install project dependencies
RUN composer install --prefer-dist --no-progress --no-interaction

# Copy the rest of the application code from LaravelMavericksFront to the working directory
COPY LaravelMavericksFront/ ./

# Set permissions for storage and bootstrap cache
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
